import type { StudioThemePreset, StudioThemeTokenMap } from './theme-preset.types.js';

export const requiredStudioThemeTokenKeys = [
  'background',
  'foreground',
  'card',
  'cardForeground',
  'popover',
  'popoverForeground',
  'primary',
  'primaryForeground',
  'secondary',
  'secondaryForeground',
  'muted',
  'mutedForeground',
  'accent',
  'accentForeground',
  'destructive',
  'destructiveForeground',
  'border',
  'input',
  'ring',
  'chart1',
  'chart2',
  'chart3',
  'chart4',
  'chart5',
] as const satisfies readonly (keyof StudioThemeTokenMap)[];

const createPreset = <const T extends StudioThemePreset>(preset: T): T => preset;

export const studioThemePresets = [
  createPreset({
    id: 'cohere',
    sourceSlug: 'cohere',
    label: 'Cohere',
    designMdPath: 'src/theme/generated/cohere/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/cohere/source-manifest.json',
    tokenMap: {
      background: '#ffffff',
      foreground: '#17171c',
      card: '#eeece7',
      cardForeground: '#212121',
      popover: '#ffffff',
      popoverForeground: '#17171c',
      primary: '#003c33',
      primaryForeground: '#ffffff',
      secondary: '#edfce9',
      secondaryForeground: '#003c33',
      muted: '#f1f5ff',
      mutedForeground: '#616161',
      accent: '#ff7759',
      accentForeground: '#17171c',
      destructive: '#b30000',
      destructiveForeground: '#ffffff',
      border: '#d9d9dd',
      input: '#e5e7eb',
      ring: '#4c6ee6',
      chart1: '#003c33',
      chart2: '#1863dc',
      chart3: '#ff7759',
      chart4: '#071829',
      chart5: '#9b60aa',
    },
    preview: {
      appearance: 'light',
      summary: 'Enterprise AI editorial white space with green-black product contrast.',
      swatches: ['#ffffff', '#003c33', '#eeece7', '#ff7759'],
      typography: {
        displayFont: 'CohereText',
        bodyFont: 'Unica77 Cohere Web',
        monoFont: 'CohereMono',
      },
    },
  }),
  createPreset({
    id: 'x-ai',
    sourceSlug: 'x.ai',
    label: 'x.ai',
    designMdPath: 'src/theme/generated/x-ai/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/x-ai/source-manifest.json',
    tokenMap: {
      background: '#0a0a0a',
      foreground: '#ffffff',
      card: '#191919',
      cardForeground: '#dadbdf',
      popover: '#1a1c20',
      popoverForeground: '#ffffff',
      primary: '#ffffff',
      primaryForeground: '#0a0a0a',
      secondary: '#1a1c20',
      secondaryForeground: '#dadbdf',
      muted: '#212327',
      mutedForeground: '#7d8187',
      accent: '#ff7a17',
      accentForeground: '#0a0a0a',
      destructive: '#ff7a17',
      destructiveForeground: '#0a0a0a',
      border: '#212327',
      input: '#363a3f',
      ring: '#a0c3ec',
      chart1: '#ff7a17',
      chart2: '#7c3aed',
      chart3: '#a0c3ec',
      chart4: '#ffc285',
      chart5: '#c4b5fd',
    },
    preview: {
      appearance: 'dark',
      summary: 'Near-black engineered canvas with white polarity and dusk accents.',
      swatches: ['#0a0a0a', '#ffffff', '#ff7a17', '#7c3aed'],
      typography: {
        displayFont: 'Universal Sans',
        bodyFont: 'Universal Sans',
        monoFont: 'monospace',
      },
    },
  }),
  createPreset({
    id: 'vercel',
    sourceSlug: 'vercel',
    label: 'Vercel',
    designMdPath: 'src/theme/generated/vercel/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/vercel/source-manifest.json',
    tokenMap: {
      background: '#ffffff',
      foreground: '#171717',
      card: '#fafafa',
      cardForeground: '#171717',
      popover: '#ffffff',
      popoverForeground: '#171717',
      primary: '#171717',
      primaryForeground: '#ffffff',
      secondary: '#f5f5f5',
      secondaryForeground: '#171717',
      muted: '#fafafa',
      mutedForeground: '#888888',
      accent: '#0070f3',
      accentForeground: '#ffffff',
      destructive: '#ee0000',
      destructiveForeground: '#ffffff',
      border: '#ebebeb',
      input: '#ebebeb',
      ring: '#0070f3',
      chart1: '#007cf0',
      chart2: '#00dfd8',
      chart3: '#7928ca',
      chart4: '#ff0080',
      chart5: '#f9cb28',
    },
    preview: {
      appearance: 'light',
      summary: 'Stark developer-platform black and white with sharp link blue.',
      swatches: ['#ffffff', '#171717', '#0070f3', '#ff0080'],
      typography: {
        displayFont: 'Geist',
        bodyFont: 'Geist',
        monoFont: 'Geist Mono',
      },
    },
  }),
  createPreset({
    id: 'clickhouse',
    sourceSlug: 'clickhouse',
    label: 'ClickHouse',
    designMdPath: 'src/theme/generated/clickhouse/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/clickhouse/source-manifest.json',
    tokenMap: {
      background: '#0a0a0a',
      foreground: '#ffffff',
      card: '#1a1a1a',
      cardForeground: '#e6e6e6',
      popover: '#121212',
      popoverForeground: '#ffffff',
      primary: '#faff69',
      primaryForeground: '#0a0a0a',
      secondary: '#242424',
      secondaryForeground: '#ffffff',
      muted: '#121212',
      mutedForeground: '#888888',
      accent: '#faff69',
      accentForeground: '#0a0a0a',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#2a2a2a',
      input: '#3a3a3a',
      ring: '#faff69',
      chart1: '#faff69',
      chart2: '#22c55e',
      chart3: '#3b82f6',
      chart4: '#f59e0b',
      chart5: '#ef4444',
    },
    preview: {
      appearance: 'dark',
      summary: 'High-performance black database shell with electric yellow voltage.',
      swatches: ['#0a0a0a', '#faff69', '#1a1a1a', '#3b82f6'],
      typography: {
        displayFont: 'sans-serif',
        bodyFont: 'sans-serif',
        monoFont: 'monospace',
      },
    },
  }),
  createPreset({
    id: 'hashicorp',
    sourceSlug: 'hashicorp',
    label: 'HashiCorp',
    designMdPath: 'src/theme/generated/hashicorp/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/hashicorp/source-manifest.json',
    tokenMap: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#15181e',
      cardForeground: '#b2b6bd',
      popover: '#1f232b',
      popoverForeground: '#ffffff',
      primary: '#ffffff',
      primaryForeground: '#000000',
      secondary: '#1f232b',
      secondaryForeground: '#ffffff',
      muted: '#252830',
      mutedForeground: '#656a76',
      accent: '#7b42bc',
      accentForeground: '#ffffff',
      destructive: '#e62b1e',
      destructiveForeground: '#ffffff',
      border: '#3b3d45',
      input: '#252830',
      ring: '#2b89ff',
      chart1: '#7b42bc',
      chart2: '#ffcf25',
      chart3: '#14c6cb',
      chart4: '#1868f2',
      chart5: '#00ca8e',
    },
    preview: {
      appearance: 'dark',
      summary: 'Infrastructure-black system with product-color identity accents.',
      swatches: ['#000000', '#7b42bc', '#ffcf25', '#14c6cb'],
      typography: {
        displayFont: 'hashicorpSans',
        bodyFont: 'hashicorpSans',
        monoFont: 'monospace',
      },
    },
  }),
  createPreset({
    id: 'sentry',
    sourceSlug: 'sentry',
    label: 'Sentry',
    designMdPath: 'src/theme/generated/sentry/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/sentry/source-manifest.json',
    tokenMap: {
      background: '#1f1633',
      foreground: '#ffffff',
      card: '#150f23',
      cardForeground: '#bdb8c0',
      popover: '#150f23',
      popoverForeground: '#ffffff',
      primary: '#150f23',
      primaryForeground: '#ffffff',
      secondary: '#362d59',
      secondaryForeground: '#ffffff',
      muted: '#3f3849',
      mutedForeground: '#bdb8c0',
      accent: '#c2ef4e',
      accentForeground: '#150f23',
      destructive: '#fa7faa',
      destructiveForeground: '#150f23',
      border: '#362d59',
      input: '#3f3849',
      ring: '#9dc1f5',
      chart1: '#c2ef4e',
      chart2: '#fa7faa',
      chart3: '#6a5fc1',
      chart4: '#79628c',
      chart5: '#9dc1f5',
    },
    preview: {
      appearance: 'dark',
      summary: 'Purple developer-tool midnight with lime and sticker-like contrast.',
      swatches: ['#1f1633', '#c2ef4e', '#fa7faa', '#6a5fc1'],
      typography: {
        displayFont: 'custom display sans',
        bodyFont: 'Rubik',
        monoFont: 'Monaco',
      },
    },
  }),
  createPreset({
    id: 'cal',
    sourceSlug: 'cal',
    label: 'Cal',
    designMdPath: 'src/theme/generated/cal/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/cal/source-manifest.json',
    tokenMap: {
      background: '#ffffff',
      foreground: '#111111',
      card: '#f5f5f5',
      cardForeground: '#111111',
      popover: '#ffffff',
      popoverForeground: '#111111',
      primary: '#111111',
      primaryForeground: '#ffffff',
      secondary: '#f8f9fa',
      secondaryForeground: '#374151',
      muted: '#f3f4f6',
      mutedForeground: '#6b7280',
      accent: '#3b82f6',
      accentForeground: '#ffffff',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#3b82f6',
      chart1: '#3b82f6',
      chart2: '#10b981',
      chart3: '#f59e0b',
      chart4: '#ec4899',
      chart5: '#8b5cf6',
    },
    preview: {
      appearance: 'light',
      summary: 'Calendar-first SaaS white canvas with black CTAs and soft cards.',
      swatches: ['#ffffff', '#111111', '#f5f5f5', '#3b82f6'],
      typography: {
        displayFont: 'Cal Sans',
        bodyFont: 'sans-serif',
        monoFont: null,
      },
    },
  }),
  createPreset({
    id: 'linear-app',
    sourceSlug: 'linear.app',
    label: 'Linear',
    designMdPath: 'src/theme/generated/linear-app/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/linear-app/source-manifest.json',
    tokenMap: {
      background: '#010102',
      foreground: '#f7f8f8',
      card: '#0f1011',
      cardForeground: '#d0d6e0',
      popover: '#141516',
      popoverForeground: '#f7f8f8',
      primary: '#5e6ad2',
      primaryForeground: '#ffffff',
      secondary: '#18191a',
      secondaryForeground: '#d0d6e0',
      muted: '#191a1b',
      mutedForeground: '#8a8f98',
      accent: '#828fff',
      accentForeground: '#ffffff',
      destructive: '#f24c53',
      destructiveForeground: '#ffffff',
      border: '#23252a',
      input: '#34343a',
      ring: '#5e69d1',
      chart1: '#5e6ad2',
      chart2: '#828fff',
      chart3: '#7a7fad',
      chart4: '#27a644',
      chart5: '#34343a',
    },
    preview: {
      appearance: 'dark',
      summary: 'Near-black product craft with restrained lavender-blue focus.',
      swatches: ['#010102', '#5e6ad2', '#0f1011', '#f7f8f8'],
      typography: {
        displayFont: 'Linear custom sans',
        bodyFont: 'SF Pro Display',
        monoFont: 'monospace',
      },
    },
  }),
  createPreset({
    id: 'framer',
    sourceSlug: 'framer',
    label: 'Framer',
    designMdPath: 'src/theme/generated/framer/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/framer/source-manifest.json',
    tokenMap: {
      background: '#090909',
      foreground: '#ffffff',
      card: '#141414',
      cardForeground: '#ffffff',
      popover: '#1c1c1c',
      popoverForeground: '#ffffff',
      primary: '#ffffff',
      primaryForeground: '#000000',
      secondary: '#1c1c1c',
      secondaryForeground: '#ffffff',
      muted: '#141414',
      mutedForeground: '#999999',
      accent: '#0099ff',
      accentForeground: '#ffffff',
      destructive: '#ff5577',
      destructiveForeground: '#ffffff',
      border: '#262626',
      input: '#1a1a1a',
      ring: '#0099ff',
      chart1: '#0099ff',
      chart2: '#d44df0',
      chart3: '#6a4cf5',
      chart4: '#ff7a3d',
      chart5: '#22c55e',
    },
    preview: {
      appearance: 'dark',
      summary: 'Dark builder artboard with white pills and blue selection energy.',
      swatches: ['#090909', '#ffffff', '#0099ff', '#d44df0'],
      typography: {
        displayFont: 'GT Walsheim',
        bodyFont: 'GT Walsheim',
        monoFont: null,
      },
    },
  }),
  createPreset({
    id: 'stripe',
    sourceSlug: 'stripe',
    label: 'Stripe',
    designMdPath: 'src/theme/generated/stripe/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/stripe/source-manifest.json',
    tokenMap: {
      background: '#ffffff',
      foreground: '#0d253d',
      card: '#f6f9fc',
      cardForeground: '#0d253d',
      popover: '#ffffff',
      popoverForeground: '#0d253d',
      primary: '#533afd',
      primaryForeground: '#ffffff',
      secondary: '#f6f9fc',
      secondaryForeground: '#273951',
      muted: '#f6f9fc',
      mutedForeground: '#64748d',
      accent: '#665efd',
      accentForeground: '#ffffff',
      destructive: '#ea2261',
      destructiveForeground: '#ffffff',
      border: '#e3e8ee',
      input: '#a8c3de',
      ring: '#533afd',
      chart1: '#533afd',
      chart2: '#f96bee',
      chart3: '#ea2261',
      chart4: '#003770',
      chart5: '#9b6829',
    },
    preview: {
      appearance: 'light',
      summary: 'Financial-infrastructure white and navy with electric indigo action.',
      swatches: ['#ffffff', '#533afd', '#0d253d', '#f96bee'],
      typography: {
        displayFont: 'Sohne',
        bodyFont: 'Sohne',
        monoFont: 'tabular numeric',
      },
    },
  }),
  createPreset({
    id: 'spotify',
    sourceSlug: 'spotify',
    label: 'Spotify',
    designMdPath: 'src/theme/generated/spotify/DESIGN.md',
    sourceManifestPath: 'src/theme/generated/spotify/source-manifest.json',
    tokenMap: {
      background: '#121212',
      foreground: '#ffffff',
      card: '#181818',
      cardForeground: '#ffffff',
      popover: '#1f1f1f',
      popoverForeground: '#ffffff',
      primary: '#1ed760',
      primaryForeground: '#121212',
      secondary: '#1f1f1f',
      secondaryForeground: '#ffffff',
      muted: '#252525',
      mutedForeground: '#b3b3b3',
      accent: '#1db954',
      accentForeground: '#121212',
      destructive: '#f3727f',
      destructiveForeground: '#121212',
      border: '#4d4d4d',
      input: '#7c7c7c',
      ring: '#1ed760',
      chart1: '#1ed760',
      chart2: '#539df5',
      chart3: '#ffa42b',
      chart4: '#f3727f',
      chart5: '#b3b3b3',
    },
    preview: {
      appearance: 'dark',
      summary: 'Immersive music-player darkness where green is the only system accent.',
      swatches: ['#121212', '#1ed760', '#181818', '#ffffff'],
      typography: {
        displayFont: 'SpotifyMixUITitle',
        bodyFont: 'SpotifyMixUI',
        monoFont: null,
      },
    },
  }),
] as const satisfies readonly StudioThemePreset[];

export type StudioThemePresetId = (typeof studioThemePresets)[number]['id'];

export const studioThemePresetIds = studioThemePresets.map((preset) => preset.id);

const studioThemePresetIdSet: ReadonlySet<string> = new Set(studioThemePresetIds);

export const isStudioThemePresetId = (value: unknown): value is StudioThemePresetId =>
  typeof value === 'string' && studioThemePresetIdSet.has(value);

export const getStudioThemePreset = (id: StudioThemePresetId): StudioThemePreset =>
  studioThemePresets.find((preset) => preset.id === id) ?? studioThemePresets[0];
